In [2]:
import numpy as np

In [6]:
# 1. Import numpy as np and see the version
# Difficulty Level: L1

# Q. Import numpy as np and print the version number.
np.__version__

'1.26.4'

In [8]:
# 2. How to create a 1D array?
# Difficulty Level: L1
# Q. Create a 1D array of numbers from 0 to 9
arr_1d=np.arange(10)
print(arr_1d)

[0 1 2 3 4 5 6 7 8 9]


In [12]:
# 3. How to create a boolean array?
# Difficulty Level: L1
# Q. Create a 3×3 numpy array of all True’s
bool_array=np.full((3,3),True, dtype=bool)
print(bool_array)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [18]:
# 4. How to extract items that satisfy a given condition from 1D array?
# Difficulty Level: L1
# Q. Extract all odd numbers from arr
# Input:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
odd_array=arr[arr%2==1]
print(odd_array)

[1 3 5 7 9]


In [28]:
# 5. How to replace items that satisfy a condition with another value in numpy array?
# Difficulty Level: L1
# Q. Replace all odd numbers in arr with -1
# Input:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
odd_array=np.where(arr%2==1,-1,arr)#arr[arr % 2 == 1] = -1
print(odd_array)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [30]:
#6. Q. Replace all odd numbers in arr with -1 without changing arr
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
y=np.arange(11,21,1)
out = np.where(arr%2==0,arr,y)##it is a condition if condition success first parameter goes failures second parameters
print(out)

[ 0 12  2 14  4 16  6 18  8 20]


In [32]:
#7 Q. Convert a 1D array to a 2D array with 2 rows
arr_1d=np.arange(10)
print("1D array: ",arr_1d)
arr_2d=arr_1d.reshape(2,5)
print("2D array: ",arr_2d)
arr_2d_1=arr_1d.reshape(2,-1)#-1 decides automatically columns size
print("2D-array: ",arr_2d_1)

1D array:  [0 1 2 3 4 5 6 7 8 9]
2D array:  [[0 1 2 3 4]
 [5 6 7 8 9]]
2D-array:  [[0 1 2 3 4]
 [5 6 7 8 9]]


In [34]:
# 8. How to stack two arrays vertically?
# Difficulty Level: L2
# Q. Stack arrays a and b vertically
a=np.arange(10,dtype=np.int64).reshape(2,-1)
b=np.arange(11,21,dtype=np.int64).reshape(2,-1)
c=np.vstack([a,b])
print("c: ",c)

c:  [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [36]:
# 9. How to stack two arrays horizontally?
# Difficulty Level: L2
# Q. Stack the arrays a and b horizontally.
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)#repeat function repeates "1" 10-times, if the first parameter is an np array, then it repeats all the elements specified times
print("a: ",a)
print("b: ",b)
c=np.hstack([a,b])
print("c: ",c)

a:  [[0 1 2 3 4]
 [5 6 7 8 9]]
b:  [[1 1 1 1 1]
 [1 1 1 1 1]]
c:  [[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


In [95]:
# 10. How to generate custom sequences in numpy without hardcoding?
# Difficulty Level: L2
# Q. Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
# Input:
# a = np.array([1,2,3])`
# Desired Output:
# #> array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
a=np.array([1,2,3])
b=np.repeat(a,3)#[1,1,1,2,2,2,,3,3,3]
c=np.tile(a,3)#[1,2,3,1,2,3,1,2,3]
d=np.concatenate([b,c])
print(d)
##shortcut is np.r_[np.repeat(a, 3), np.tile(a, 3)],np.r_ is a convenience function for concatenation along the first axis.

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


In [48]:
# 11. How to get the common items between two python numpy arrays?
# Difficulty Level: L2
# Q. Get the common items between a and b
# Input:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
common_array=np.intersect1d(a,b)
print(common_array)

[2 4]


In [50]:
# 12. How to remove from one array those items that exist in another?
# Difficulty Level: L2
# Q. From array a remove all items present in array b
# Input:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
# From 'a' remove all of 'b'
c=np.setdiff1d(a,b)
print(c)

[1 2 3 4]


In [54]:
# 13. How to get the positions where elements of two arrays index match?
# Difficulty Level: L2
# Q. Get the positions where elements of a and b match
# Input:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
c=np.where(a==b)
print(c)

(array([1, 3, 5, 7], dtype=int64),)


In [108]:
# 14. How to extract all numbers between a given range from a numpy array?
# Difficulty Level: L2
# Q. Get all items between 5 and 10 from a.
# Input:
a = np.array([2, 6, 1, 9, 10, 3, 27])
index=np.where((a>=5) & (a<=10))
print(a[index])

[ 6  9 10]


In [122]:
# 15. How to make a python function that handles scalars to work on numpy arrays?
# Difficulty Level: L2
# Q. Convert the function maxx that works on two scalars, to work on two arrays.
# Input:
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y
maxx(1, 5)
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
c=np.where(a>b,a,b)
print(c)

pair_max = np.vectorize(maxx, otypes=[float])
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
print(pair_max(a, b))


[6 7 9 8 9 7 5]
[6. 7. 9. 8. 9. 7. 5.]


In [136]:
# 16. How to swap two columns in a 2d numpy array?
# Difficulty Level: L2
# Q. Swap columns 1 and 2 in the array arr.
arr = np.arange(9).reshape(3,3)
swapped_array=arr.swapaxes(0,1)
print(swapped_array)
#or
# Solution
arr[:, [1,0,2]]

[[0 3 6]
 [1 4 7]
 [2 5 8]]


array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [132]:
# 17. How to swap two rows in a 2d numpy array?
# Difficulty Level: L2
# Q. Swap rows 1 and 2 in the array arr:
arr = np.arange(9).reshape(3,3)
swapped_2d_array=arr[[1,0,2],:]
print(swapped_2d_array)

[[3 4 5]
 [0 1 2]
 [6 7 8]]


In [146]:
# 18. How to reverse the rows of a 2D array?
# Difficulty Level: L2
# Q. Reverse the rows of a 2D array arr.
# Input
arr = np.arange(9).reshape(3,3)
reversed_array=arr[:,[2,1,0]]
print(reversed_array)
#or 
print(arr[::-1])

[[2 1 0]
 [5 4 3]
 [8 7 6]]
[[6 7 8]
 [3 4 5]
 [0 1 2]]


In [148]:
# 19. How to reverse the columns of a 2D array?
# Difficulty Level: L2
# Q. Reverse the columns of a 2D array arr.
# Input
arr = np.arange(9).reshape(3,3)
columns_reverse=arr[:,::-1]
print(columns_reverse)

[[2 1 0]
 [5 4 3]
 [8 7 6]]


In [162]:
# 20. How to create a 2D array containing random floats between 5 and 10?
# Difficulty Level: L2
# Q. Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.
random_array_int=np.random.randint(low=5,high=10,size=(5,3))
random_array_floats=np.random.random((5,3))
print(random_array_int+random_array_floats)

[[6.5734626  5.53746707 5.33585574]
 [5.64036046 7.85102293 9.01521303]
 [5.40771579 6.74623879 8.12583241]
 [9.62356475 7.53420816 6.60613326]
 [6.45837064 8.12865148 9.20759879]]


In [178]:
# 21. How to print only 3 decimal places in python numpy array?
# Difficulty Level: L1
# Q. Print or show only 3 decimal places of the numpy array rand_arr.
# Input:
rand_arr = np.random.random((5,3))
np.set_printoptions(precision=3)
print(rand_arr)

[[0.403 0.677 0.167]
 [0.791 0.802 0.499]
 [0.806 0.097 0.924]
 [0.946 0.63  0.376]
 [0.945 0.563 0.663]]


In [227]:
# 22. How to pretty print a numpy array by suppressing the scientific notation (like 1e10)?
# Difficulty Level: L1
# Q. Pretty print rand_arr by suppressing the scientific notation (like 1e10)
np.random.seed(10)
rand_arr = np.random.random([3,3])/1e3
print(rand_arr)
np.set_printoptions(suppress=True, precision=6)  # precision is optional
print(rand_arr)

[[7.713e-04 2.075e-05 6.336e-04]
 [7.488e-04 4.985e-04 2.248e-04]
 [1.981e-04 7.605e-04 1.691e-04]]
[[0.000771 0.000021 0.000634]
 [0.000749 0.000499 0.000225]
 [0.000198 0.000761 0.000169]]


In [247]:
# 23. How to limit the number of items printed in output of numpy array?
# Difficulty Level: L1
# Q. Limit the number of items printed in python numpy array a to a maximum of 6 elements.
# Input:
a = np.arange(15)
np.set_printoptions(threshold=6)
print(a)

[ 0  1  2 ... 12 13 14]


In [269]:
# 24. How to print the full numpy array without truncating
# Difficulty Level: L1
# Q. Print the full numpy array a without truncating.
# Input:
np.set_printoptions(threshold=6)
a = np.arange(18)
print(a)
np.set_printoptions(threshold=a.size)
print(a)

[ 0  1  2 ... 15 16 17]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]


In [275]:
# 25. How to import a dataset with numbers and texts keeping the text intact in python numpy?
# Difficulty Level: L2
# Q. Import the iris dataset keeping the text intact.
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
# Print the first 3 rows
iris[:3]

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa']], dtype=object)

In [326]:
# 26. How to extract a particular column from 1D array of tuples?
# Difficulty Level: L2
# Q. Extract the text column species from the 1D iris imported in previous question.
# Input:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None,encoding='utf-8')
print(iris_1d.shape)
species = np.array([row[4] for row in iris_1d])
species[:5]

(150,)


array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa'], dtype='<U15')

In [344]:
# 27. How to convert a 1d array of tuples to a 2d numpy array?
# Difficulty Level: L2
# Q. Convert the 1D iris to 2D array iris_2d by omitting the species text field.
# Input:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None,usecols=[0,1,2,3],encoding='utf-8')
print(iris_1d[:4])
# Solution:
# Method 1: Convert each row to a list and get the first 4 items
iris_2d = np.array([row.tolist()[:4] for row in iris_1d])
print(iris_2d[:4])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]]
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]]


In [352]:
# 28. How to compute the mean, median, standard deviation of a numpy array?
# Q. Find the mean, median, standard deviation of iris's sepallength (1st column)
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype=None,usecols=[0,1,2,3])
print
iris_mean=np.mean(iris,axis=0)
print(iris_mean)
iris_median=np.median(iris, axis=1)
print(iris_median)
iris_std=np.std(iris)
print(iris_std)


[5.843333 3.054    3.758667 1.198667]
[2.45 2.2  2.25 ... 4.1  4.4  4.05]
1.974000985027335


In [396]:
# 29. How to normalize an array so the values range exactly between 0 and 1?
# Difficulty: L2
# Q. Create a normalized form of iris's sepallength whose values range exactly between 0 and 1 so that the minimum has value 0 and maximum has value 1.
# Input:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])
#print(sepallength)
# Solution
smax, smin = sepallength.max(), sepallength.min()
# Normalizing the array normalizaton means arranging all the value between 0 to 1 formula is (element-minvalue)/(max-min)
normalized_arr = (sepallength -smin) / (smax - smin)
print(normalized_arr)

[0.222222 0.166667 0.111111 ... 0.611111 0.527778 0.444444]


In [398]:
# 30. How to compute the softmax score?
# Difficulty Level: L3
# Q. Compute the softmax score of sepallength.
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
sepallength = np.array([float(row[0]) for row in iris])

# Solution
def softmax(x):
    """Compute softmax values for each sets of scores in x.
    https://stackoverflow.com/questions/34968722/how-to-implement-the-softmax-function-in-python"""
    e_x = np.exp(x - np.max(x))
    return e_x / e_x.sum(axis=0)

print(softmax(sepallength))

[0.00222  0.001817 0.001488 ... 0.009001 0.006668 0.00494 ]


In [414]:
# 31. How to find the percentile scores of a numpy array?
# Difficulty Level: L1
# Q. Find the 5th and 95th percentile of iris's sepallength
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])
#solution
np.percentile(sepallength,q=[5,95])

array([4.6  , 7.255])

In [469]:
# 32. How to insert values at random positions in an array?
# Difficulty Level: L2
# Q. Insert np.nan values at 20 random positions in iris_2d dataset
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='object')
x= np.random.random((3,3))###generates floating nump array size 3x3,
y=np.random.randint(1,10,size=(3,3))##generates integer numpy array size 3x3
random_position=np.random.randint(2,size=2)#prints random number single item
print(random_position)
print(x)
print(y)
iris_2d[random_position[0]][random_position[1]]=np.nan
print(iris_2d[random_position[0]][random_position[1]])

[1 1]
[[0.184868 0.840247 0.569271]
 [0.06005  0.988917 0.228782]
 [0.614702 0.368027 0.802776]]
[[3 6 9]
 [2 8 2]
 [8 2 9]]
nan


In [477]:
# 33. How to find the position of missing values in numpy array?
# Difficulty Level: L2
# Q. Find the number and position of missing values in iris_2d's sepallength (1st column)
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float')
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan
# Solution
print("Number of missing of values: ",np.isnan(iris_2d[:,0]).sum())
print("Positions of missing values: ",np.where(np.isnan(iris_2d[:,0])))

Number of missing of values:  3
Positions of missing values:  (array([  0,  56, 109], dtype=int64),)


In [479]:
# 34. How to filter a numpy array based on two or more conditions?
# Difficulty Level: L3
# Q. Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
# Solution
condition = (iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)
iris_2d[condition]

array([[4.8, 3.4, 1.6, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [4.9, 2.5, 4.5, 1.7]])

In [483]:
# 35. How to drop rows that contain a missing value from a numpy array?
# Difficulty Level: L3: 
# Q. Select the rows of iris_2d that does not have any nan value.
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
# Solution
# No direct numpy function for this.
# Method 1:
any_nan_in_row = np.array([~np.any(np.isnan(row)) for row in iris_2d])
iris_2d[any_nan_in_row][:5]

# Method 2: (By Rong)
iris_2d[np.sum(np.isnan(iris_2d), axis = 1) == 0][:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [491]:
# 36. How to find the correlation between two columns of a numpy array?
# Difficulty Level: L2
# Q. Find the correlation between SepalLength(1st column) and PetalLength(3rd column) in iris_2d
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='int', usecols=[0,1,2,3])
print(np.corrcoef(iris_2d[:, 0], iris_2d[:, 2])[0, 1])

0.7883455241438413


In [493]:
# 37. How to find if a given array has any null values?
# Difficulty Level: L2
# Q. Find out if iris_2d has any missing values.
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
np.isnan(iris_2d).any()

False

In [495]:
# 38. How to replace all missing values with 0 in a numpy array?
# Difficulty Level: L2
# Q. Replace all ccurrences of nan with 0 in numpy array
# Solution
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
np.isnan(iris_2d).any()
iris_2d[np.isnan(iris_2d)] = 0
iris_2d[:4]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2]])

In [497]:
# 39. How to find the count of unique values in a numpy array?
# Difficulty Level: L2
# Q. Find the unique values and the count of unique values in iris's species
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
# Solution
# Extract the species column as an array
species = np.array([row.tolist()[4] for row in iris])
# Get the unique values and the counts
np.unique(species, return_counts=True)

(array([b'Iris-setosa', b'Iris-versicolor', b'Iris-virginica'],
       dtype='|S15'),
 array([50, 50, 50], dtype=int64))

In [501]:
# 40. How to convert a numeric to a categorical (text) array?
# Difficulty Level: L2
# Q. Bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:
# Less than 3 --> 'small'
# 3-5 --> 'medium'
# '>=5 --> 'large'
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
# Bin petallength 
petal_length_bin = np.digitize(iris[:, 2].astype('float'), [0, 3, 5, 10])

# Map it to respective category
label_map = {1: 'small', 2: 'medium', 3: 'large', 4: np.nan}
petal_length_cat = [label_map[x] for x in petal_length_bin]

# View
petal_length_cat[:4]

['small', 'small', 'small', 'small']