In [6]:
#Import basic modules
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split

In [1]:
#Implementation of Logistic Regression Algorithm

In [7]:
from sklearn.datasets import load_breast_cancer
from sklearn.linear_model import LogisticRegression

In [8]:
data=load_breast_cancer()

In [14]:
#Creating a dataset for breast cancer data set
df=pd.concat([pd.DataFrame(data.data),pd.DataFrame(data.target)],axis=1)
df.head()

0      1       2       3        4        5       6        7       8   \
0  17.99  10.38  122.80  1001.0  0.11840  0.27760  0.3001  0.14710  0.2419   
1  20.57  17.77  132.90  1326.0  0.08474  0.07864  0.0869  0.07017  0.1812   
2  19.69  21.25  130.00  1203.0  0.10960  0.15990  0.1974  0.12790  0.2069   
3  11.42  20.38   77.58   386.1  0.14250  0.28390  0.2414  0.10520  0.2597   
4  20.29  14.34  135.10  1297.0  0.10030  0.13280  0.1980  0.10430  0.1809   

        9   ...     21      22      23      24      25      26      27  \
0  0.07871  ...  17.33  184.60  2019.0  0.1622  0.6656  0.7119  0.2654   
1  0.05667  ...  23.41  158.80  1956.0  0.1238  0.1866  0.2416  0.1860   
2  0.05999  ...  25.53  152.50  1709.0  0.1444  0.4245  0.4504  0.2430   
3  0.09744  ...  26.50   98.87   567.7  0.2098  0.8663  0.6869  0.2575   
4  0.05883  ...  16.67  152.20  1575.0  0.1374  0.2050  0.4000  0.1625   

       28       29  0   
0  0.4601  0.11890   0  
1  0.2750  0.08902   0  
2  0.3613  0.08758   0  
3  0.6638  0.17300   0  
4  0.2364  0.07678   0  

[5 rows x 31 columns]

In [15]:
X=data.data
Y=data.target

In [18]:
X_train,X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.2,random_state=42)

In [20]:
#training the model
model=LogisticRegression()
model.fit(X_train,Y_train)

D:\Anaconda\envs\ML-Env\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [22]:
y_pred=model.predict(X_test)
y_pred

array([1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 0, 0])

In [24]:
accuracy = model.score(X_test,Y_test)
print("Accuracy: ",accuracy)

Accuracy:  0.956140350877193


In [25]:
####Implementation of Linear Descriminant Analysis

In [26]:
#It is a generative model, 
#works fine in  lesser number of features

In [27]:
#Load the model breast cancer.,
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

In [28]:
lda_model = LinearDiscriminantAnalysis()
lda_model.fit(X,Y)

LinearDiscriminantAnalysis()

In [31]:
X_lda=lda_model.transform(X)

In [32]:
X_train_lda,X_test_lda,Y_train_lda,Y_test_lda = train_test_split(X_lda,Y,test_size=0.2, random_state=42)

In [34]:
classifier = LogisticRegression()
classifier.fit(X_train_lda,Y_train)

LogisticRegression()

In [39]:
classifier.predict(X_test_lda)

array([1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 0])

In [42]:
print(classifier.score(X_test_lda,Y_test_lda))

0.9736842105263158


In [43]:
####Implementation of Stochastic Gradient Descent Classifier

In [46]:
from sklearn.linear_model import SGDClassifier
from sklearn.datasets import make_classification

In [47]:
#Generate a binary classification dataset
X,y=make_classification(n_samples=1000,n_features=10,n_classes=2,random_state=42)

In [58]:
X_train,X_test,Y_train,Y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [61]:
### we are setting hyper-parameters for SGD Classifier
model=SGDClassifier(loss='log_loss',penalty='l2',alpha=0.0001,max_iter=1000,tol=1e-3,random_state=42)
##log--for binary
###l2--for ridge regularization
##aplha is related to learning rate ===>0.0001
##max_iter refers to 1000 for no of iterations
##tolarance is 1e-3

In [62]:
model.fit(X_train,Y_train)

SGDClassifier(loss='log_loss', random_state=42)

In [63]:
y_pred=model.predict(X_test)
y_pred

array([0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0,
       0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1,
       1, 1])