In [2]:
import numpy as np

In [3]:
#create a list of 1000000 integers
list_1=list(range(1000000))

In [4]:
#create a numpy array
array_1=np.arange(100000)

In [5]:
#Numpy ARRAYS AND METHODS

In [6]:
#create an array range from 0 to 9
arr =np.arange(0,10,3)#  same as range
print(arr)
new_arr=np.arange(-4,-10,-2,dtype=int)
print(new_arr)

[0 3 6 9]
[-4 -6 -8]


In [7]:
# 1D ARRAYS
arr_1d=np.array([1,2,3,4,5,6])
print(arr_1d)

[1 2 3 4 5 6]


In [8]:
#2d array
arr_2d=np.array([[1,2,3],[4,5,6],[6,7,8]])
print(arr_2d)
arr_2d[2]

[[1 2 3]
 [4 5 6]
 [6 7 8]]


array([6, 7, 8])

In [9]:
#properties of nd arrays

1. Shape

In [10]:
arr_2d=np.array([[1,2,4],[4,5,6]])
#shape of an 2d array
shape=arr_2d.shape
print(shape)

(2, 3)


2. Data Type

In [11]:
arr_float=np.arange(0,10,0.5,dtype=float)
print(arr_float)
arr_float_1=np.array([1.1,2.2,3.3],dtype=np.float32)
print(arr_float_1)
print(arr_float.dtype,arr_float_1.dtype)
arr_ints=np.array([1.04,2.12,3.12],dtype=int)
print(arr_ints,arr_ints.dtype)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5
 9.  9.5]
[1.1 2.2 3.3]
float64 float32
[1 2 3] int64


3. Size

In [12]:
arr_3d=np.zeros((2,3,4))
print(arr_3d,arr_3d.size)##2*3*4=24

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]] 24


In [13]:
arr_4d=np.ones((2,3,4,2))
print(arr_4d,arr_4d.size,arr_4d.shape,arr_4d.dtype)#2*3*4*2=48

[[[[1. 1.]
   [1. 1.]
   [1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]
   [1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]
   [1. 1.]
   [1. 1.]]]


 [[[1. 1.]
   [1. 1.]
   [1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]
   [1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]
   [1. 1.]
   [1. 1.]]]] 48 (2, 3, 4, 2) float64


5.Itemsize

In [14]:
arr_int=np.array([1,2,3])
print(arr_int.dtype)
##print the item size
print("size of each element: ",arr_int.itemsize)#output : 8 (for 64-bit integer)

int64
size of each element:  8


6. Precision

In [15]:
arr_int32=np.array([1234567890,1234567890],dtype=np.int32)
arr_int64=np.array([1234567890,1234567890],dtype=np.int64)
print("memory usage for 32 type: ",arr_int32.itemsize*arr_int.size,"bytes")
print("memory usage for 64 type: ",arr_int64.itemsize*arr_int.size,"bytes")

memory usage for 32 type:  12 bytes
memory usage for 64 type:  24 bytes


7. Zeros, ones, full

In [16]:
arr_zeros=np.zeros([2,3], dtype=np.int64) #default if float64
print(arr_zeros)

[[0 0 0]
 [0 0 0]]


In [17]:
arr_zeros=np.ones([2,3],dtype=np.float64)
print(arr_zeros)

[[1. 1. 1.]
 [1. 1. 1.]]


In [18]:
#np.full create an array filled with a speified constant value , 
#it takes the shape of desired array and the constant value as input and
#return an array of that shape filled with the specified value

In [19]:
arr_const=np.full((2,3),5,dtype=np.float32)
print(arr_const)

[[5. 5. 5.]
 [5. 5. 5.]]


In [20]:
arr_of_4d_const=np.full((2,3,4),1.23,dtype=np.float32)
print(arr_of_4d_const)

[[[1.23 1.23 1.23 1.23]
  [1.23 1.23 1.23 1.23]
  [1.23 1.23 1.23 1.23]]

 [[1.23 1.23 1.23 1.23]
  [1.23 1.23 1.23 1.23]
  [1.23 1.23 1.23 1.23]]]


ARRAY OPERATIONS

1. Arithmatic Operations

In [21]:
arr_1=np.array([1,2,3],dtype=np.int64)
arr_2=np.array([[4,5,6],[1,1,1]],dtype=np.int64)

#addition
arr_add=np.add(arr_1,arr_2,dtype=np.int32)
print("addition: ",arr_add)


#subtraction
arr_sub=np.subtract(arr_1,arr_2,dtype=np.float64)
print("subtraction: ",arr_sub)
#multiplication
arr_mul=np.multiply(arr_1,arr_2,dtype=np.float64)
print("multily: ",arr_mul)

#division
arr_div=np.divide(arr_1,arr_2)
print("division: ",arr_div)

#Modulus %
arr_mod=np.mod(arr_1,arr_2,dtype=np.float64)
print("modulus: ",arr_mod)

#Exponent i.e power
arr_pow=np.power(arr_1,arr_2,dtype=np.float64)
print("power: ",arr_pow)

addition:  [[5 7 9]
 [2 3 4]]
subtraction:  [[-3. -3. -3.]
 [ 0.  1.  2.]]
multily:  [[ 4. 10. 18.]
 [ 1.  2.  3.]]
division:  [[0.25 0.4  0.5 ]
 [1.   2.   3.  ]]
modulus:  [[1. 2. 3.]
 [0. 0. 0.]]
power:  [[  1.  32. 729.]
 [  1.   2.   3.]]


2. RELATIONAL OPERATORS

In [22]:
arr_1=np.array([1,2,3,4])
arr_2=np.array([2,3,3,4])
## equality
print("Equal: ",arr_1==arr_2)#element by elelmenvt comparision

##not eqaul
print("Not equal: ",arr_1!=arr_2)#element by element comparision

## greater than
print("Greater than",arr_1>arr_2)##element by element comparision

##less than
print("Less than: ",arr_1<arr_2)##element by elementcomparision

##greater than equal to 
print("greater than or equal: ",arr_1>=arr_2) #element by element comparision

##less that or equal
print("less than or equal : ",arr_1<=arr_2) #element by elemnt comaparision

Equal:  [False False  True  True]
Not equal:  [ True  True False False]
Greater than [False False False False]
Less than:  [ True  True False False]
greater than or equal:  [False False  True  True]
less than or equal :  [ True  True  True  True]


Indexing and slicing 1D Arrays

1. INDEXING

In [23]:
arr_1d=np.array([[1,2,3],[4,5,6]])
print(arr_1d[0][1])
print(arr_1d[1])


2
[4 5 6]


2. SLICING

In [24]:
arr_1d=np.array([[1,2,3,4,5,6,7,8,9],[0,0,0,0,0,0,0,0,0],[1,1,1,1,1,1,1,1,1]],dtype=np.int64)
print("Slice: ",arr_1d[0][1:6:2])
print("with step size: ",arr_1d[1][0:4:2])

Slice:  [2 4 6]
with step size:  [0 0]


3. Negative Indexing

In [25]:
arr_neg=np.array([1,2,3],dtype=np.int64)
print(arr_neg[-1])

3


4. Slicing with Omitted Indices

In [26]:
arr_1=np.array([1,2,3,4,5,6,7,8,9],dtype=np.int64)
print(arr_1[::3])
print(arr_1[2::2])
print(arr_1[::2])#considers whole array

[1 4 7]
[3 5 7 9]
[1 3 5 7 9]


INDEXING AND SLICING 2D ARRAY

In [27]:
arr_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr_2d[0,0])
print(arr_2d[1,2])

1
6


In [28]:
##slicing

In [29]:
print(arr_2d[0:2,0:2])

[[1 2]
 [4 5]]


In [30]:
#modify slice
arr_2d[0:2,0:2]=[[10,20],[30,40]]
print(arr_2d)

[[10 20  3]
 [30 40  6]
 [ 7  8  9]]


In [31]:
#negative indexes

In [32]:
print(arr_2d[::-1,::-1])###reverse of 2d array
print(arr_2d[-1, -1])##accesing last element[row, column]
print(arr_2d[-1,-2])

[[ 9  8  7]
 [ 6 40 30]
 [ 3 20 10]]
9
8


In [33]:
#slicing with omitted indices
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[1::])
print(arr[:,0:2:2])

[[4 5 6]
 [7 8 9]]
[[1]
 [4]
 [7]]


Mass Level indexing and slicing

In [34]:
arr_m=np.array([1,2,3,4,5])
print(arr_m>2)

[False False  True  True  True]


In [35]:
arr_2m=np.array([[1,2,3],[4,5,6]])
print(arr_2m>=2)

[[False  True  True]
 [ True  True  True]]


In [36]:
arr_1d=np.array([1,2,3,4,5,6])
print(arr_1d[[0,2,4]])

[1 3 5]


In [42]:
arr_2d=np.array([[1,2,3,],[4,5,6]])
print(arr_2d[[0,1]])

[[1 2 3]
 [4 5 6]]


In [59]:
#Transpose of a matrix
arr_2d=np.array([[1,2,3],[4,5,6]])
arr_transpose=arr_2d.T
print(arr_2d)
print(arr_transpose)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [47]:
#swaping

In [60]:
print(arr_2d.swapaxes(0,1))

[[1 4]
 [2 5]
 [3 6]]


In [69]:
arr_3d=np.array([[[1,2,3,0],[4,5,6,1],[7,8,9,2]],[[10,11,12,3],[13,14,15,4],[16,17,18,5]]])
print(arr_3d.shape)
swapped_arr_3d=np.swapaxes(arr_3d,0,1)
print(swapped_arr_3d.shape)
print(swapped_arr_3d)

(2, 3, 4)
(3, 2, 4)
[[[ 1  2  3  0]
  [10 11 12  3]]

 [[ 4  5  6  1]
  [13 14 15  4]]

 [[ 7  8  9  2]
  [16 17 18  5]]]


In [70]:
#random generators

In [72]:
random_integers=np.random.randint(1,10,size=5)
print(random_integers)

[1 5 8 2 9]


In [89]:
random_normal=np.random.normal(10,3,size=(2,2,3))#two2d array
print(random_normal)

[[[ 8.83021004 13.02258208 11.34422559]
  [10.74057801 11.76004139  9.36808974]]

 [[ 3.31706119  7.15159974 15.81895904]
  [11.44843073 12.40128606 14.50928478]]]


In [95]:
#Matrix multiplication:
arr_1=np.array([[1,2,3],[4,5,6]])
print(arr_1.shape)
arr_2=np.array([[7,8],[-1,-3],[-2,-4]])
print(arr_2.shape,arr_2.size)
arr_3=np.matmul(arr_1,arr_2)
print(arr_3)

(2, 3)
(3, 2) 6
[[ -1 -10]
 [ 11  -7]]


In [98]:
#reshape of a matrix
arr=np.arange(1,10)
print(arr)
reshape_arr=arr.reshape(3,3)
print(reshape_arr)
reshape_arr=arr.reshape(3,2)
print(reshape_arr)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


ValueError: cannot reshape array of size 9 into shape (3,2)

In [102]:
###Transpose of matrix
arr=np.array([[1,2,3],[4,5,6]])
transpose_arr=arr.T
print(transpose_arr)
transpose_1=np.transpose(arr)
print(transpose_1)

[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]


In [103]:
#Aggregate Functions

In [104]:
matrix=np.array([[1,2,3],[6,5,6]])
print("sum of all elements: ",np.sum(matrix))
print("maximum element: ",np.max(matrix))
print("minimum element: ",np.min(matrix))
print("mean of all elements: ",np.mean(matrix))

sum of all elements:  23
maximum element:  6
minimum element:  1
mean of all elements:  3.8333333333333335


In [105]:
#universal functions

In [109]:
#trigonometric functions
angles=np.array([0,np.pi/3,np.pi/2,np.pi/4])
print(angles)
result_sin=np.sin(angles)
print(result_sin)
result_cos=np.cos(angles)
print(result_cos)

[0.         1.04719755 1.57079633 0.78539816]
[0.         0.8660254  1.         0.70710678]
[1.00000000e+00 5.00000000e-01 6.12323400e-17 7.07106781e-01]


In [110]:
#exponential and logorithmic

In [114]:
result_exp=np.exp(angles)
print(result_exp)
result_logs=np.log(arr)
print(result_logs)

[1.         2.84965391 4.81047738 2.19328005]
[[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]]


In [115]:
##statistical functions

In [117]:
arr_2d=np.array([[1,2,3,4],[2,3,4,5]])
result_mean=np.mean(arr_2d)
print(result_mean)
result_median=np.median(arr_2d)
print(result_median)
result_std=np.std(arr)
print(result_std)

3.0
3.0
1.707825127659933


In [118]:
#Comparision Functions

In [123]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([2,3,3,4,4])
#greater than
result_gt =np.greater(arr1,arr2)
print(result_gt)
result_less=np.less_equal(arr1,arr2)
print(result_less)

[False False False False  True]
[ True  True  True  True False]


In [124]:
#Broadcasting

In [131]:
arr=np.arange(1,10)
print(arr)

[1 2 3 4 5 6 7 8 9]


In [132]:
arr=arr+2
arr

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11])

In [136]:
a=np.resize(arr,(2,5))
print(a)

[[ 3  4  5  6  7]
 [ 8  9 10 11  3]]


In [140]:
#ravel and flattened
a=np.array([[1,2],[3,4]])

##ravel changes the original one
## flattened created a new one and modifies new one
b=a.ravel()
b[0]=100
print("raveled: ",a,"b: ",b)


c=a.flatten()
c[1]=200
print("flatten: ",a,"c: ",c)

print(c.squeeze())


raveled:  [[100   2]
 [  3   4]] b:  [100   2   3   4]
flatten:  [[100   2]
 [  3   4]] c:  [100 200   3   4]
[100 200   3   4]


In [141]:
##splitting and joining

In [145]:
#np.split splits into multiple arrays
x=np.arange(9)
x_split=np.split(x,3)##equal arrays
print(x_split)
x_array_split=np.array_split(x,4)###unequal subarray
print(x_array_split)


y=np.array([[1,2,3],[4,5,6]])

###horizontal split
h_split=np.hsplit(y,3)
print(h_split)
v_split=np.vsplit(y,2)
print(v_split)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]
[array([0, 1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]
[array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]
[array([[1, 2, 3]]), array([[4, 5, 6]])]


In [150]:
##concatenate
arr_3=np.concatenate((x,x))
print(arr_3)
a=np.arange(0,3,1)
b=np.arange(3,6,1)
print("horizontally stacked: ",np.hstack((a,b)))
print("verticallly stacked: ",np.vstack((a,b)))

[0 1 2 3 4 5 6 7 8 0 1 2 3 4 5 6 7 8]
horizontally stacked:  [0 1 2 3 4 5]
verticallly stacked:  [[0 1 2]
 [3 4 5]]


In [151]:
##adding and removing elements
a=np.array([[1,2]])

##adding
appended =np.append(a,[7,8])
print(appended)
inserted=np.insert(a,1,[9,10])
print(inserted)
deleted=np.delete(a,1)#delete(a,[0,3],axis=0) delete multiplt indices, 0-->horixontal,1-->vertical
print(deleted)

[1 2 7 8]
[ 1  9 10  2]
[1]
