In [6]:
import numpy as np
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [32]:
#step 1 creating a complex data set
np.random.seed(0)
x=np.linspace(0,10,100) #Independent variable
print(x)
y = 3*x**2+2*x+np.random.normal(0,10,100)
print(y)

[ 0.          0.1010101   0.2020202   0.3030303   0.4040404   0.50505051
  0.60606061  0.70707071  0.80808081  0.90909091  1.01010101  1.11111111
  1.21212121  1.31313131  1.41414141  1.51515152  1.61616162  1.71717172
  1.81818182  1.91919192  2.02020202  2.12121212  2.22222222  2.32323232
  2.42424242  2.52525253  2.62626263  2.72727273  2.82828283  2.92929293
  3.03030303  3.13131313  3.23232323  3.33333333  3.43434343  3.53535354
  3.63636364  3.73737374  3.83838384  3.93939394  4.04040404  4.14141414
  4.24242424  4.34343434  4.44444444  4.54545455  4.64646465  4.74747475
  4.84848485  4.94949495  5.05050505  5.15151515  5.25252525  5.35353535
  5.45454545  5.55555556  5.65656566  5.75757576  5.85858586  5.95959596
  6.06060606  6.16161616  6.26262626  6.36363636  6.46464646  6.56565657
  6.66666667  6.76767677  6.86868687  6.96969697  7.07070707  7.17171717
  7.27272727  7.37373737  7.47474747  7.57575758  7.67676768  7.77777778
  7.87878788  7.97979798  8.08080808  8.18181818  8

In [41]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [43]:
model =LinearRegression()
x_train = x_train.reshape(-1,1) #this is to reshape into a 2D format
model.fit(x_train,y_train)

LinearRegression()

In [44]:
x_test=x_test.reshape(-1,1)
y_pred=model.predict(x_test)

In [45]:
y_pred

array([222.36025784, 123.18687249, 179.38512419,  96.7406364 ,
        93.43485689,  76.90595933,  20.70770763, 212.44291931,
       -18.96164651, -52.01944162,   7.48458959,  47.15394373,
       189.30246273,  57.07128226, 245.50071443, -38.79632358,
       199.21980126, 202.52558077, -12.35008748,  50.45972324])

In [46]:
x_test

array([[8.38383838],
       [5.35353535],
       [7.07070707],
       [4.54545455],
       [4.44444444],
       [3.93939394],
       [2.22222222],
       [8.08080808],
       [1.01010101],
       [0.        ],
       [1.81818182],
       [3.03030303],
       [7.37373737],
       [3.33333333],
       [9.09090909],
       [0.4040404 ],
       [7.67676768],
       [7.77777778],
       [1.21212121],
       [3.13131313]])

POLYNOMIAL REGRESSION

In [49]:
import matplotlib.pyplot as plt
import numpy as np
from sklearn.preprocessing import PolynomialFeatures
from sklearn.model_selection import train_test_split 
from sklearn.linear_model import LinearRegression

In [50]:
np.random.seed(0)
x=np.linspace(0,10,100)
y=3*x**2+2*x+np.random.normal(0,10,100)

In [51]:
x=x.reshape(-1,1)
y=y.reshape(-1,1)

In [52]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [60]:
#transform the independent variable X into polynomial features
poly_features = PolynomialFeatures(degree=2)
x_train_poly = poly_features.fit_transform(x_train)
x_test_poly = poly_features.transform(x_test)

In [61]:
x_train_poly.shape

(80, 3)

In [63]:
x_test_poly.shape

(20, 3)

In [69]:
y_train_pred = model.predict(x_train_poly)
y_test_pred= model.predict(x_test_poly)

In [76]:
#visualization
trace_train = go.Scatter(x=x_train.flatten(),y=y_train.flatten(),mode='markers',name='Training Data',marker=dict(color='blue'))
trace_test = go.Scatter(x=x_test.flatten(),y=y_test.flatten(),mode='markers',name='Testing Data',marker=dict(color='blue'))
trace_regression = go.Scatter(x=x_train.flatten(),y=y_train_pred.flatten(),mode='lines',name='Polynomial Regression',marker={'color':'red'})
layout = go.Layout(title='Polynomial Regression',xaxis=dict(title='X'),yaxis=dict(title='Y'))
figure = go.Figure(data=[trace_train,trace_test,trace_regression],layout=layout)

figure.show()



In [77]:
####Ridge Regression

In [87]:
import pandas as pd
from sklearn.datasets import load_diabetes
data = load_diabetes()
x = pd.DataFrame(data.data,columns=data.feature_names)
y = pd.DataFrame(data.target,columns=['target'])

In [90]:
x

age       sex       bmi        bp        s1        s2        s3  \
0    0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1   -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2    0.085299  0.050680  0.044451 -0.005670 -0.045599 -0.034194 -0.032356   
3   -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4    0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   
..        ...       ...       ...       ...       ...       ...       ...   
437  0.041708  0.050680  0.019662  0.059744 -0.005697 -0.002566 -0.028674   
438 -0.005515  0.050680 -0.015906 -0.067642  0.049341  0.079165 -0.028674   
439  0.041708  0.050680 -0.015906  0.017293 -0.037344 -0.013840 -0.024993   
440 -0.045472 -0.044642  0.039062  0.001215  0.016318  0.015283 -0.028674   
441 -0.045472 -0.044642 -0.073030 -0.081413  0.083740  0.027809  0.173816   

           s4        s5        s6  
0   -0.002592  0.019907 -0.017646  
1   -0.039493 -0.068332 -0.092204  
2   -0.002592  0.002861 -0.025930  
3    0.034309  0.022688 -0.009362  
4   -0.002592 -0.031988 -0.046641  
..        ...       ...       ...  
437 -0.002592  0.031193  0.007207  
438  0.034309 -0.018114  0.044485  
439 -0.011080 -0.046883  0.015491  
440  0.026560  0.044529 -0.025930  
441 -0.039493 -0.004222  0.003064  

[442 rows x 10 columns]

In [91]:
y

target
0     151.0
1      75.0
2     141.0
3     206.0
4     135.0
..      ...
437   178.0
438   104.0
439   132.0
440   220.0
441    57.0

[442 rows x 1 columns]

In [92]:
X_train,X_test, Y_train, Y_test = train_test_split(x, y, test_size=0.2,random_state =0)

In [103]:
from sklearn.linear_model import Ridge
regressor = Ridge(alpha=1.0)
regressor.fit(X_train,Y_train)

Ridge()

In [104]:
X_train.shape

(353, 10)

In [105]:
Y_train.shape

(353, 1)

In [106]:
X_test.shape

(89, 10)

In [107]:
Y_test.shape

(89, 1)

In [108]:
y_pred = regressor.predict(X_test)
y_pred

array([[202.19243848],
       [207.28630959],
       [161.85088977],
       [129.14913352],
       [160.20479927],
       [206.91305258],
       [121.64923725],
       [178.86958078],
       [139.1497849 ],
       [186.11181219],
       [146.63593877],
       [178.18055742],
       [122.59137575],
       [105.34843675],
       [218.85962646],
       [113.26596793],
       [143.16786932],
       [ 92.36986679],
       [105.66751174],
       [200.63465568],
       [168.41731228],
       [144.08203737],
       [158.09140374],
       [139.64999223],
       [181.89664258],
       [159.8321348 ],
       [124.83093593],
       [106.17262305],
       [166.12691858],
       [163.36804787],
       [171.56695934],
       [105.95939673],
       [135.97171488],
       [145.13042454],
       [156.28547912],
       [174.37730888],
       [159.75060544],
       [177.84220497],
       [139.23219223],
       [183.04315648],
       [108.70320759],
       [168.37897879],
       [150.03615784],
       [162

Lasso Regression

In [110]:
from sklearn.datasets import load_diabetes
from sklearn.linear_model import Lasso
from sklearn.model_selection import train_test_split
import pandas as pd

In [117]:
data = load_diabetes()
X = pd.DataFrame(data=data.data, columns=data.feature_names)
Y = pd.DataFrame(data=data,columns=['target'])

In [118]:
X

age       sex       bmi        bp        s1        s2        s3  \
0    0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1   -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2    0.085299  0.050680  0.044451 -0.005670 -0.045599 -0.034194 -0.032356   
3   -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4    0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   
..        ...       ...       ...       ...       ...       ...       ...   
437  0.041708  0.050680  0.019662  0.059744 -0.005697 -0.002566 -0.028674   
438 -0.005515  0.050680 -0.015906 -0.067642  0.049341  0.079165 -0.028674   
439  0.041708  0.050680 -0.015906  0.017293 -0.037344 -0.013840 -0.024993   
440 -0.045472 -0.044642  0.039062  0.001215  0.016318  0.015283 -0.028674   
441 -0.045472 -0.044642 -0.073030 -0.081413  0.083740  0.027809  0.173816   

           s4        s5        s6  
0   -0.002592  0.019907 -0.017646  
1   -0.039493 -0.068332 -0.092204  
2   -0.002592  0.002861 -0.025930  
3    0.034309  0.022688 -0.009362  
4   -0.002592 -0.031988 -0.046641  
..        ...       ...       ...  
437 -0.002592  0.031193  0.007207  
438  0.034309 -0.018114  0.044485  
439 -0.011080 -0.046883  0.015491  
440  0.026560  0.044529 -0.025930  
441 -0.039493 -0.004222  0.003064  

[442 rows x 10 columns]

In [119]:
Y

target
0     151.0
1      75.0
2     141.0
3     206.0
4     135.0
..      ...
437   178.0
438   104.0
439   132.0
440   220.0
441    57.0

[442 rows x 1 columns]

In [120]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=0)

In [121]:
regressor = Lasso(alpha=1.0)
regressor.fit(X_train,Y_train)

Lasso()

In [125]:
Y_pred = regressor.predict(X_test)

In [126]:
Y_pred

array([196.06915657, 200.37220201, 149.4164878 , 129.31375659,
       158.90084765, 212.51348311, 129.70449222, 174.5846108 ,
       149.09961684, 192.35581107, 142.59757187, 173.06625567,
       126.17197144, 115.67923848, 198.06761992, 118.40888575,
       128.37687532, 107.76747917,  96.34504789, 167.82137554,
       153.10744239, 162.14365074, 150.83402606, 158.51105293,
       195.14193663, 171.59967425, 130.4168034 , 119.09716969,
       163.41053135, 165.76386   , 160.1045647 , 107.32591407,
       133.2272528 , 149.49818308, 160.26651667, 164.86452983,
       150.10625809, 151.72359603, 137.12306269, 176.18668968,
       114.69127891, 154.51641021, 163.53542656, 162.3721378 ,
       156.3833375 , 107.89703119, 150.02555483, 148.26885356,
       141.74500756, 174.67854132, 143.67881764, 111.3582612 ,
       140.01689147, 158.54177212, 183.91732433, 156.63179153,
       175.4855262 , 132.90027728, 146.7661563 , 172.21156402,
       180.10697338, 156.31100694, 154.45329107, 138.80

#Elastic Net Regression

In [131]:
from sklearn.linear_model import ElasticNet

In [129]:
X_train, X_test,Y_train,Y_test = train_test_split(X,Y, test_size=0.3)

In [139]:
elastic_net = ElasticNet(alpha=0.5,l1_ratio = 0.5,max_iter=10000,random_state=0)

In [140]:
elastic_net.fit(X_train,Y_train)

ElasticNet(alpha=0.5, max_iter=10000, random_state=0)

In [141]:
y_pred=elastic_net.predict(X_test)

In [142]:
y_pred

array([155.39535937, 153.78017315, 153.92344511, 153.03551112,
       153.58376691, 152.13127641, 155.98836905, 156.66192611,
       152.22979045, 152.27814634, 156.19909907, 153.2344302 ,
       152.48714124, 153.35295656, 153.9328108 , 155.42670399,
       151.68740339, 153.04207835, 154.80741709, 153.42741992,
       154.20945981, 153.09621438, 152.88302405, 153.8594126 ,
       152.79652257, 152.62135879, 155.72556367, 152.78196993,
       154.38835011, 154.40893005, 155.87898245, 153.45960395,
       153.56913701, 151.86631048, 155.19208636, 154.83259632,
       154.53904006, 154.60050195, 154.54914777, 155.94333044,
       154.17200265, 152.73465468, 155.04665312, 154.4274989 ,
       152.52903542, 155.43469411, 153.00774039, 152.99960142,
       154.0640211 , 151.6727798 , 154.93606192, 151.83407387,
       154.58438274, 153.13055038, 153.9843691 , 154.42253515,
       154.20576158, 155.56606251, 153.02677874, 153.64225494,
       155.48979212, 152.82713689, 152.72751564, 151.98