In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf

In [5]:
tf.__version__

'2.6.0'

# Initialization of Tensors; 

In [6]:
# Tensor is a block i.e., matrix is a 2-d tensor, it deals with multidimensional matrix

In [9]:
x = tf.constant(4,shape=(1,1),dtype=tf.float32)
print(x)

tf.Tensor([[4.]], shape=(1, 1), dtype=float32)


In [10]:
x = tf.constant([[1,2,3],[4,5,6]])
print(x)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [11]:
x=tf.ones((3,3))
print(x)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)


In [12]:
x=tf.zeros((4,4),dtype=tf.int32)
print(x)

tf.Tensor(
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]], shape=(4, 4), dtype=int32)


In [15]:
#Diagonal Matrix-->Identity Matrix
x= tf.eye(3,dtype=tf.int32)
print(x)

tf.Tensor(
[[1 0 0]
 [0 1 0]
 [0 0 1]], shape=(3, 3), dtype=int32)


In [18]:
x=tf.random.normal((3,3,4),mean=0,stddev=1)
print(x)

tf.Tensor(
[[[ 1.4041435   0.8687842  -0.07121728  2.6743412 ]
  [-1.2606591  -0.22486812 -0.7531717  -0.7393049 ]
  [-1.4843378   0.21935464  1.0852717  -0.45238912]]

 [[ 2.0888069  -1.2516321   0.43353587  0.20234208]
  [ 1.5346272  -0.7958654   0.6912642   0.38069308]
  [ 0.25091043  0.57131785  0.32084414  1.410375  ]]

 [[-1.6549871   0.79934436 -0.7210671   1.0706489 ]
  [ 1.4287065  -0.3231162   0.50502235 -0.1588261 ]
  [-1.0127802   0.42589936 -0.6386313   0.41154116]]], shape=(3, 3, 4), dtype=float32)


In [19]:
x = tf.random.uniform((1,3),minval=0,maxval=1)
print(x)

tf.Tensor([[0.00111163 0.1933626  0.7007195 ]], shape=(1, 3), dtype=float32)


In [20]:
x = tf.range(start=1,limit=10,delta=2)#delta means step
print(x)

tf.Tensor([1 3 5 7 9], shape=(5,), dtype=int32)


In [21]:
#convert to float
x= tf.cast(x,dtype=tf.float64)
print(x)

tf.Tensor([1. 3. 5. 7. 9.], shape=(5,), dtype=float64)


In [22]:
#tf.bool, tf.int, tf.float, tf.str

# Mathematical Operations

In [24]:
x = tf.random.normal((1,3),dtype=tf.float32)
y = tf.random.normal((1,3),dtype=tf.float32)
print(x)
print(y)

tf.Tensor([[-2.5873785  -0.49811095  0.9998711 ]], shape=(1, 3), dtype=float32)
tf.Tensor([[ 1.0251312  -0.63749504 -0.21273768]], shape=(1, 3), dtype=float32)


In [25]:
z = tf.add(x,y)
print(z)

tf.Tensor([[-1.5622473 -1.135606   0.7871334]], shape=(1, 3), dtype=float32)


In [26]:
z = x+y
print(z)

tf.Tensor([[-1.5622473 -1.135606   0.7871334]], shape=(1, 3), dtype=float32)


In [27]:
#Subtract
z=tf.subtract(x,y)
print(z)

tf.Tensor([[-3.6125097   0.13938409  1.2126088 ]], shape=(1, 3), dtype=float32)


In [28]:
z=x-y
print(z)

tf.Tensor([[-3.6125097   0.13938409  1.2126088 ]], shape=(1, 3), dtype=float32)


In [29]:
x = tf.constant([1,2,3])
y = tf.constant([4,5,6])
print(x)
print(y)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor([4 5 6], shape=(3,), dtype=int32)


In [30]:
z = tf.divide(x,y)
print(z)

tf.Tensor([0.25 0.4  0.5 ], shape=(3,), dtype=float64)


In [31]:
z = x/y
print(z)

tf.Tensor([0.25 0.4  0.5 ], shape=(3,), dtype=float64)


In [32]:
z =x//y
print(z)

tf.Tensor([0 0 0], shape=(3,), dtype=int32)


In [33]:
z = tf.multiply(x,y)
print(z)

tf.Tensor([ 4 10 18], shape=(3,), dtype=int32)


In [34]:
z = x*y
print(z)

tf.Tensor([ 4 10 18], shape=(3,), dtype=int32)


In [35]:
z = tf.tensordot(x,y,axes=1)
print(z)

tf.Tensor(32, shape=(), dtype=int32)


In [38]:
z = tf.reduce_sum(x*y,axis=0)
print(z)

tf.Tensor(32, shape=(), dtype=int32)


In [39]:
z= x**5
print(z)

tf.Tensor([  1  32 243], shape=(3,), dtype=int32)


In [40]:
x = tf.random.normal((2,3))
y = tf.random.normal((3,4))
z = tf.matmul(x,y)
print(z)
z = x@y
print(z)

tf.Tensor(
[[ 0.19166541  1.7318048   0.4118823  -0.40468472]
 [-0.11959159 -3.329309    1.914173   -2.1547046 ]], shape=(2, 4), dtype=float32)
tf.Tensor(
[[ 0.19166541  1.7318048   0.4118823  -0.40468472]
 [-0.11959159 -3.329309    1.914173   -2.1547046 ]], shape=(2, 4), dtype=float32)


# Indexing a Tensor

In [49]:
x = tf.constant([0,1,2,3,4,5,6,7,8,9])
print(x[:])

tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)


In [42]:
print(x[:3])

tf.Tensor([0 1 2], shape=(3,), dtype=int32)


In [43]:
print(x[::-1])

tf.Tensor([9 8 7 6 5 4 3 2 1 0], shape=(10,), dtype=int32)


In [44]:
print(x[::2])

tf.Tensor([0 2 4 6 8], shape=(5,), dtype=int32)


In [51]:
indices = tf.constant([0,3])
x_ind = tf.gather(x,indices)#gather values at that indices
print(x_ind)

tf.Tensor([0 3], shape=(2,), dtype=int32)


In [46]:
x = tf.constant([[1,2],[3,4],[5,6]])
print(x[0,:])
print(x[0:2,:])

tf.Tensor([1 2], shape=(2,), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [52]:
#Reshaping
x =tf.range(9)
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)


In [54]:
x = tf.reshape(x,(3,3))
print(x)

tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)


In [56]:
#Transponse
x = tf.transpose(x,perm=[1,0])
print(x)

tf.Tensor(
[[0 3 6]
 [1 4 7]
 [2 5 8]], shape=(3, 3), dtype=int32)


# Neural Networks with Sequential and Functional API

In [57]:
# import os
# os.envrion['TFF_CPP_MIN_LOG_LEVEL'] = '2'
# minimizes os warning toward tf

###if device troubleshoots for GPU the exicute these two lines of code
# physical_devices = tf.config.list_physical_devices('GPU')
# tf.config.experiments.set_memory_growth(physical_devices[0],True)

In [75]:
# Sequential API means single Input and single ouput

In [59]:
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.datasets import mnist

In [60]:
(x_train,y_train),(x_test,y_test)=mnist.load_data()
print(x_train.shape)
print(x_test.shape)

11501568/11490434 [==============================] - 4s 0us/step
(60000, 28, 28)
(10000, 28, 28)


In [104]:
# normalizing _train x_test between 0,1

In [61]:
x_train =x_train.reshape(-1,28*28).astype("float32")/ 255.0
x_test = x_test.reshape(-1,28*28).astype("float32")/255.0

In [72]:
# Sequential API (Very Convenient, not very flexible)
model = keras.Sequential(
    [
        keras.Input(shape=(28*28)),#input layer
        layers.Dense(512,activation='relu'),#hidden layer 1
        layers.Dense(256,activation='relu'),#hidden layer 2
        layers.Dense(10),#ouput layer
    ]
)
print(model.summary())

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_6 (Dense)              (None, 512)               401920    
_________________________________________________________________
dense_7 (Dense)              (None, 256)               131328    
_________________________________________________________________
dense_8 (Dense)              (None, 10)                2570      
Total params: 535,818
Trainable params: 535,818
Non-trainable params: 0
_________________________________________________________________
None


In [74]:
#The above code can be written as 
model=keras.Sequential()
model.add(keras.Input(shape=(784)))#28*28=784
model.add(layers.Dense(512,activation='relu'))
model.add(layers.Dense(256,activation='relu'))
model.add(layers.Dense(10))

In [67]:
#compile model means compiling and training that network model
model.compile(
    loss = keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer=keras.optimizers.Adam(learning_rate=0.001),
    metrics=['accuracy'],
)

In [69]:
model.fit(x_train,y_train,batch_size=32,epochs=5,verbose=2)

Epoch 1/5
1875/1875 - 11s - loss: 0.0268 - accuracy: 0.9913
Epoch 2/5
1875/1875 - 6s - loss: 0.0228 - accuracy: 0.9929
Epoch 3/5
1875/1875 - 8s - loss: 0.0206 - accuracy: 0.9933
Epoch 4/5
1875/1875 - 7s - loss: 0.0199 - accuracy: 0.9939
Epoch 5/5
1875/1875 - 10s - loss: 0.0180 - accuracy: 0.9944


# Functional API
multiple input --> multiple output

In [88]:
inputs = keras.Input(shape=(784))
x = layers.Dense(512,activation='relu',name='first_layer')(inputs)#adding previous layer here
x = layers.Dense(256,activation='relu',name='second_layer')(x)#adding previous layer x here
outputs = layers.Dense(10,activation='softmax')(x)# adding previous layer here

In [89]:
model = keras.Model(inputs=inputs,outputs=outputs)

In [90]:
#compile model means compiling and training that network model
model.compile(
    loss = keras.losses.SparseCategoricalCrossentropy(from_logits=False),
    optimizer=keras.optimizers.Adam(learning_rate=0.001),
    metrics=['accuracy'],
)

In [85]:
model.fit(x_train,y_train,batch_size=32,epochs=5,verbose=2)

Epoch 1/5
1875/1875 - 8s - loss: 0.1864 - accuracy: 0.9438
Epoch 2/5
1875/1875 - 10s - loss: 0.0801 - accuracy: 0.9750
Epoch 3/5
1875/1875 - 10s - loss: 0.0535 - accuracy: 0.9830
Epoch 4/5
1875/1875 - 9s - loss: 0.0407 - accuracy: 0.9868
Epoch 5/5
1875/1875 - 10s - loss: 0.0352 - accuracy: 0.9887


In [92]:
model.summary()

Model: "model_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_8 (InputLayer)         [(None, 784)]             0         
_________________________________________________________________
first_layer (Dense)          (None, 512)               401920    
_________________________________________________________________
second_layer (Dense)         (None, 256)               131328    
_________________________________________________________________
dense_22 (Dense)             (None, 10)                2570      
Total params: 535,818
Trainable params: 535,818
Non-trainable params: 0
_________________________________________________________________


In [93]:
# extract specific layer outputs
model = keras.Model(inputs=inputs,outputs=[model.layers[-1].output])#-1 means last layer, -2 means second last layer, same as indexing
feature = model.predict(x_train)
print(feature.shape)

(60000, 10)


In [95]:
#extract by named layers
model= keras.Model(inputs=inputs,outputs=[model.get_layer('first_layer').output])
feature = model.predict(x_train)
print(feature.shape)

(60000, 512)


In [99]:
#all LAYERS ouputs
model = keras.Model(inputs=inputs,outputs=[layer.output for layer in model.layers])
features = model.predict(x_train)

for feature in features:
    print(feature.shape)


(60000, 784)
(60000, 512)


# CNN-Convolutional Nueral Networks with Sequential and Functional API

In [101]:
from tensorflow.keras.datasets import cifar10

In [103]:
(x_train,x_test),(y_train,y_test) = cifar10.load_data()
x_train = x_train.astype('float32')/255.0
x_test = x_test.astype('float32')/255.0

Exception: URL fetch failure on https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz: None -- [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

In [111]:
model = keras.Sequential(
    [
        keras.Input(shape=(32,32,3)),#we are dealing with images so 32 width, 32 height, 3 color channels i.e, RGB
        layers.Conv2D(32,3,padding='valid',activation='relu'),#output channels 32, kernel_size =3 means(3,3),padding is 'valid' or 'same' 
        layers.MaxPool2D(pool_size=(2,2)),
        layers.Conv2D(64,3,padding='valid',activation='relu'),
        layers.MaxPool2D(),
        layers.Conv2D(128,3,padding='valid',activation='relu'),
        layers.MaxPool2D(),
        layers.Flatten(),
        layers.Dense(64,activation='relu'),
        layers.Dense(10),
    ]
)

In [110]:
print(model.summary())

Model: "sequential_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 30, 30, 32)        896       
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 15, 15, 32)        0         
Total params: 896
Trainable params: 896
Non-trainable params: 0
_________________________________________________________________
None


In [112]:
#compile model means compiling and training that network model
model.compile(
    loss = keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer=keras.optimizers.Adam(learning_rate=3e-4),
    metrics=['accuracy'],
)

In [120]:
model.fit(x_train,y_train,batch_size=64,epochs=10,verbose=2)
model.evaluate(x_test,y_test,batch_size=64,verbose=2)

RuntimeError: You must compile your model before training/testing. Use `model.compile(optimizer, loss)`.

In [114]:
# error is beacuse data set not loading

# Using Funtional API

In [118]:
def my_model():
    inputs = keras.Input(shape=(32,32,3))
    x = layers.Conv2D(32,3)(inputs)
    x = layers.BatchNormalization()(x)
    x = keras.activations.relu(x)
    x = layers.MaxPooling2D()(x)
    x = layers.Conv2D(64,3,padding='same')(x)
    x = layers.BatchNormalization()(x)
    x = keras.activations.relu(x)
    x = layers.Conv2D(128,3)(x)
    x = layers.BatchNormalization()(x)
    x = keras.activations.relu(x)
    x = layers.Flatten()(x)
    x =layers.Dense(64,activation='relu')(x)
    outputs = layers.Dense(10)(x)
    model = keras.Model(inputs = inputs, outputs=outputs)
    return model
    

In [119]:
model = my_model()

In [ ]:
#compile model means compiling and training that network model
model.compile(
    loss = keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer=keras.optimizers.Adam(learning_rate=3e-4),
    metrics=['accuracy'],
)

In [121]:
model.fit(x_train,y_train,batch_size=64,epochs=10,verbose=2)
model.evaluate(x_test,y_test,batch_size=64,verbose=2)

RuntimeError: You must compile your model before training/testing. Use `model.compile(optimizer, loss)`.

# Adding Regularization with L2 and Dropout

In [123]:
from tensorflow.keras import layers, regularizers

In [124]:
def my_model():
    inputs = keras.Input(shape=(32,32,3))
    x = layers.Conv2D(
        32,3,padding='same',kernel_regularizer=regularizers.l2(0.01))(inputs)#0.01 is weight of that regularizer
    x = layers.BatchNormalization()(x)
    x = keras.activations.relu(x)
    x = layers.MaxPooling2D()(x)
    x = layers.Conv2D(64,3,padding='same',kernel_regularizer=regularizers.l2(0.01))(x)
    x = layers.BatchNormalization()(x)
    x = keras.activations.relu(x)
    x = layers.Conv2D(128,3,padding='same',kernel_regularizer=regularizers.l2(0.01))(x)
    x = layers.BatchNormalization()(x)#faster training
    x = keras.activations.relu(x)
    x = layers.Flatten()(x)
    x =layers.Dense(64,activation='relu',kernel_regularizer=regularizers.l2(0.01))(x)
    x = layers.Dropout(0.5)(x)#drop 0.5 connections between above and below layer
    outputs = layers.Dense(10)(x)
    model = keras.Model(inputs = inputs, outputs=outputs)
    return model

In [125]:
model = my_model()
#compile model means compiling and training that network model
model.compile(
    loss = keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer=keras.optimizers.Adam(learning_rate=3e-4),
    metrics=['accuracy'],
)
model.fit(x_train,y_train,batch_size=64,epochs=10,verbose=2)
model.evaluate(x_test,y_test,batch_size=64,verbose=2)